[build]
  base = "/"
  publish = ".dist"
  command = "npx js.new build"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Powered-By = "js.new"
